package testsupport

import "errors"

var ErrTestPurpose = errors.New("error raised in a test")
